IF EXISTS (SELECT 1 FROM SYS.DATABASES WHERE NAME = 'SiLabI')
BEGIN
	ALTER DATABASE [SiLabI] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	ALTER DATABASE [SiLabI] SET READ_ONLY;
	ALTER DATABASE [SiLabI] SET MULTI_USER;
	DROP DATABASE [SiLabI];
END
GO

IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'SilabiLogin')
	DROP LOGIN [SilabiLogin]
GO

IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'AdministratorLogin')
	DROP LOGIN [AdministratorLogin]
GO

IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'OperatorLogin')
	DROP LOGIN [OperatorLogin]
GO

IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'ProfessorLogin')
	DROP LOGIN [ProfessorLogin]
GO

IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'StudentLogin')
	DROP LOGIN [StudentLogin]
GO

IF NOT EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = 'SiLabI')
BEGIN
CREATE DATABASE [SiLabI] ON  PRIMARY 
( NAME = N'SiLabI', FILENAME = N'C:\SiLabI\SiLabI.mdf' , SIZE = 5072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SiLabI_log', FILENAME = N'C:\SiLabI\SiLabI_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
END
GO

ALTER DATABASE [SiLabI] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
	EXEC [SiLabI].[dbo].[sp_fulltext_database] @action = 'enable'
END
GO

ALTER DATABASE [SiLabI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SiLabI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SiLabI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SiLabI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SiLabI] SET ARITHABORT OFF 
GO

ALTER DATABASE [SiLabI] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SiLabI] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SiLabI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SiLabI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SiLabI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SiLabI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SiLabI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SiLabI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SiLabI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SiLabI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SiLabI] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SiLabI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SiLabI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SiLabI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SiLabI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SiLabI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SiLabI] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SiLabI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SiLabI] SET  READ_WRITE 
GO

ALTER DATABASE [SiLabI] SET RECOVERY FULL 
GO

ALTER DATABASE [SiLabI] SET  MULTI_USER 
GO

ALTER DATABASE [SiLabI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SiLabI] SET DB_CHAINING OFF 
GO

-- Create silabi login.
IF NOT EXISTS (SELECT loginname FROM syslogins WHERE name = 'SilabiLogin' and dbname = 'SiLabI')
BEGIN
	CREATE LOGIN [SilabiLogin] WITH PASSWORD = 'password', DEFAULT_DATABASE=[SiLabI], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
END
GO

-- Create administrator login.
IF NOT EXISTS (SELECT loginname FROM syslogins WHERE name = 'AdministratorLogin' and dbname = 'SiLabI')
BEGIN
	CREATE LOGIN [AdministratorLogin] WITH PASSWORD = 'password', DEFAULT_DATABASE=[SiLabI], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
END
GO

-- Create operator login.
IF NOT EXISTS (SELECT loginname FROM syslogins WHERE name = 'OperatorLogin' and dbname = 'SiLabI')
BEGIN
	CREATE LOGIN [OperatorLogin] WITH PASSWORD = 'password', DEFAULT_DATABASE=[SiLabI], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
END
GO

-- Create professor login.
IF NOT EXISTS (SELECT loginname FROM syslogins WHERE name = 'ProfessorLogin' and dbname = 'SiLabI')
BEGIN
	CREATE LOGIN [ProfessorLogin] WITH PASSWORD = 'password', DEFAULT_DATABASE=[SiLabI], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
END
GO

-- Create student login.
IF NOT EXISTS (SELECT loginname FROM syslogins WHERE name = 'StudentLogin' and dbname = 'SiLabI')
BEGIN
	CREATE LOGIN [StudentLogin] WITH PASSWORD = 'password', DEFAULT_DATABASE=[SiLabI], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
END
GO