USE [master];

ALTER DATABASE [SiLabI]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;

ALTER DATABASE [SiLabI]
SET READ_ONLY
GO

ALTER DATABASE [SiLabI]
SET MULTI_USER
GO

IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = N'WebService')
	DROP USER [WebService]
GO

IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'WebServiceLogin')
	DROP LOGIN [WebServiceLogin]
GO

IF EXISTS (SELECT 1 FROM SYS.DATABASES WHERE NAME = 'SiLabI')
	DROP DATABASE SiLabI
	GO
GO