USE [SiLabI];

INSERT INTO States (Type, Name) VALUES
('USER', 'ACTIVE'),
('USER', 'INACTIVE'),
('USER', 'BLOCKED'),
('OPERATOR', 'ACTIVE'),
('OPERATOR', 'INACTIVE'),
('ADMINISTRATOR', 'ACTIVE'),
('ADMINISTRATOR', 'INACTIVE'),
('COURSE', 'ACTIVE'),
('COURSE', 'INACTIVE'),
('GROUP', 'ACTIVE'),
('GROUP', 'INACTIVE'),
('LABORATORY', 'ACTIVE'),
('LABORATORY', 'INACTIVE'),
('SOFTWARE', 'ACTIVE'),
('SOFTWARE', 'INACTIVE'),
('APPOINTMENT', 'BEFORE_START'),
('APPOINTMENT', 'IN_PROGRESS'),
('APPOINTMENT', 'CANCELED'),
('APPOINTMENT', 'FINISHED'),
('RESERVATION', 'BEFORE_START'),
('RESERVATION', 'IN_PROGRESS'),
('RESERVATION', 'CANCELED'),
('RESERVATION', 'FINISHED');

USE [master];