using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace SiLabI.Model
{
    /// <summary>
    /// Wrapper to a paginated query.
    /// When retrieving a paginated query use this class to wrap the results and send the pagination information.
    /// </summary>
    /// <typeparam name="T">The requested type of data.</typeparam>
    [DataContract]
    public class PaginatedResponse<T>
    {
        private int _total;
        private int _current;

        /// <summary>
        /// Creates a new GetResponse
        /// </summary>
        public PaginatedResponse()
        {
            this.Results = new List<T>();
            this.TotalPages = 1;
            this.CurrentPage = 1;
        }

        /// <summary>
        /// The retrieved results.
        /// </summary>
        [DataMember(Name = "results")]
        public List<T> Results { get; set; }

        /// <summary>
        /// The amount of pages generated by the query.
        /// </summary>
        [DataMember(Name = "total_pages")]
        public int TotalPages
        {
            get { return _total; }
            set { if (value > 0) _total = value; }
        }

        /// <summary>
        /// The current page number.
        /// </summary>
        [DataMember(Name = "current_page")]
        public int CurrentPage
        {
            get { return _current; }
            set { if (value > 0) _current = value; }
        }
    }
}